"""empty message

Revision ID: 077ef770ebe7
Revises: b6e482daab49
Create Date: 2018-01-25 11:58:37.060695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077ef770ebe7'
down_revision = 'b6e482daab49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('is_enable', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('is_enable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_enable')
    op.drop_column('company', 'is_enable')
    # ### end Alembic commands ###
