"""upgrade company field

Revision ID: 19325e3a9caf
Revises: db733a122cdc
Create Date: 2018-01-21 19:30:19.752115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19325e3a9caf'
down_revision = 'db733a122cdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('company', sa.Column('summary', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_company_email'), 'company', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_email'), table_name='company')
    op.drop_column('company', 'summary')
    op.drop_column('company', 'email')
    # ### end Alembic commands ###
