"""empty message

Revision ID: 288f1f4fd03a
Revises: e72a99a9754e
Create Date: 2018-01-22 09:07:13.153816

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '288f1f4fd03a'
down_revision = 'e72a99a9754e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'address',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('company', 'email',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('company', 'website',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('user', 'job_years',
               existing_type=mysql.VARCHAR(length=2),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=18),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=18),
               nullable=False)
    op.alter_column('user', 'job_years',
               existing_type=mysql.VARCHAR(length=2),
               nullable=False)
    op.alter_column('company', 'website',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    op.alter_column('company', 'email',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.alter_column('company', 'address',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###
