"""empty message

Revision ID: 7dcc7315f2b0
Revises: 839b875ae54d
Create Date: 2018-01-21 20:57:33.956274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7dcc7315f2b0'
down_revision = '839b875ae54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_ibfk_1', 'company', type_='foreignkey')
    op.drop_column('company', 'user_id')
    op.add_column('user', sa.Column('company_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'company_id')
    op.add_column('company', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('company_ibfk_1', 'company', 'user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
