"""empty message

Revision ID: 912012809d0f
Revises: d5464e12f923
Create Date: 2018-01-25 16:49:24.134089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '912012809d0f'
down_revision = 'd5464e12f923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('field', sa.String(length=128), nullable=True))
    op.add_column('company', sa.Column('finance_stage', sa.String(length=128), nullable=True))
    op.add_column('company', sa.Column('tags', sa.String(length=128), nullable=True))
    op.drop_column('company', 'summary')
    op.add_column('job', sa.Column('location', sa.String(length=24), nullable=True))
    op.add_column('job', sa.Column('salary_high', sa.Integer(), nullable=False))
    op.add_column('job', sa.Column('salary_low', sa.Integer(), nullable=False))
    op.add_column('job', sa.Column('tags', sa.String(length=128), nullable=True))
    op.drop_column('job', 'salary')
    op.drop_column('user', 'job_years')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('job_years', mysql.VARCHAR(length=2), nullable=True))
    op.add_column('job', sa.Column('salary', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('job', 'tags')
    op.drop_column('job', 'salary_low')
    op.drop_column('job', 'salary_high')
    op.drop_column('job', 'location')
    op.add_column('company', sa.Column('summary', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('company', 'tags')
    op.drop_column('company', 'finance_stage')
    op.drop_column('company', 'field')
    # ### end Alembic commands ###
