"""empty message

Revision ID: b49d1913e109
Revises: 8905b2be33c4
Create Date: 2018-01-27 23:35:16.574216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b49d1913e109'
down_revision = '8905b2be33c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=True)
    op.drop_index('ix_user_username', table_name='user')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=32), nullable=True))
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
