"""empty message

Revision ID: b5b24d5f9952
Revises: 9b66e2fb0d9e
Create Date: 2018-01-25 10:08:17.684343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b5b24d5f9952'
down_revision = '9b66e2fb0d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('address', mysql.VARCHAR(length=64), nullable=False))
    # ### end Alembic commands ###
