"""add is_enable in User class

Revision ID: cc4887a8d792
Revises: f2a7900ab8f7
Create Date: 2018-01-22 16:20:14.946346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc4887a8d792'
down_revision = 'f2a7900ab8f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_enable', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_enable')
    # ### end Alembic commands ###
