"""empty message

Revision ID: d5464e12f923
Revises: b5b24d5f9952
Create Date: 2018-01-25 14:46:38.709221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5464e12f923'
down_revision = 'b5b24d5f9952'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('resume_url', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'resume_url')
    # ### end Alembic commands ###
