"""empty message

Revision ID: e02c7d057a2b
Revises: ef495d0a56d6
Create Date: 2018-01-26 15:01:16.622957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e02c7d057a2b'
down_revision = 'ef495d0a56d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('requirement', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'requirement')
    # ### end Alembic commands ###
