"""empty message

Revision ID: e4ee19fed0f4
Revises: 077ef770ebe7
Create Date: 2018-01-25 19:17:30.246069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4ee19fed0f4'
down_revision = '077ef770ebe7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('role', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'role')
    # ### end Alembic commands ###
