"""empty message

Revision ID: ef304dfb1e11
Revises: 8412d0c34aa2
Create Date: 2018-01-31 16:57:25.229029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef304dfb1e11'
down_revision = '8412d0c34aa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('job_ibfk_1', 'job', type_='foreignkey')
    op.create_foreign_key(None, 'job', 'user', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.create_foreign_key('job_ibfk_1', 'job', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
