"""empty message

Revision ID: ef495d0a56d6
Revises: 912012809d0f
Create Date: 2018-01-26 11:55:01.328064

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ef495d0a56d6'
down_revision = '912012809d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('is_enable', sa.Boolean(), nullable=True))
    op.add_column('job', sa.Column('is_fulltime', sa.Boolean(), nullable=True))
    op.add_column('job', sa.Column('stacks', sa.String(length=128), nullable=True))
    op.drop_column('job', 'tags')
    op.drop_column('job', 'requirement')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('requirement', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('job', sa.Column('tags', mysql.VARCHAR(length=128), nullable=True))
    op.drop_column('job', 'stacks')
    op.drop_column('job', 'is_fulltime')
    op.drop_column('job', 'is_enable')
    # ### end Alembic commands ###
